# Pandas Merge & Concatenation Practice
## E-Commerce Sales System Dataset

**Objective**: Master all concepts of merging and concatenating DataFrames in pandas

**Topics Covered**:
- Concatenation (vertical & horizontal)
- Inner Join
- Outer Join (Full)
- Left Join
- Right Join
- Multi-way merges
- Indicator parameters
- Suffix handling
- Data quality checks

**Instructions**:
1. Run the dataset creation cells first
2. Solve each question in the empty code cell below it
3. Verify your results make logical sense
4. Progress from Level 1 to Level 4

---

## Setup: Import Libraries

Import the necessary libraries for this practice session.

In [1]:
import pandas as pd
import numpy as np

# Display settings for better output
pd.set_option('display.max_columns', None)
pd.set_option('display.width', None)
pd.set_option('display.max_colwidth', None)

print("Libraries imported successfully!")

Libraries imported successfully!


---

## Dataset Creation

Run the cells below to create all datasets needed for practice.

### Dataset 1: Customer Orders

In [2]:
# Create customers_orders DataFrame
customers_orders = pd.DataFrame({
    'order_id': [1001, 1002, 1003, 1004, 1005, 1006, 1007],
    'customer_id': ['C001', 'C002', 'C001', 'C003', 'C004', 'C002', 'C005'],
    'customer_name': ['Rahul Sharma', 'Priya Patel', 'Rahul Sharma', 'Amit Kumar', 
                      'Sneha Reddy', 'Priya Patel', 'Vikram Singh'],
    'order_date': ['2025-01-05', '2025-01-06', '2025-01-08', '2025-01-09', 
                   '2025-01-10', '2025-01-11', '2025-01-12'],
    'region': ['North', 'West', 'North', 'South', 'East', 'West', 'North']
})

print("customers_orders DataFrame:")
display(customers_orders)

customers_orders DataFrame:


,order_id,customer_id,customer_name,order_date,region
0,1001,C001,Rahul Sharma,2025-01-05,North
1,1002,C002,Priya Patel,2025-01-06,West
2,1003,C001,Rahul Sharma,2025-01-08,North
3,1004,C003,Amit Kumar,2025-01-09,South
4,1005,C004,Sneha Reddy,2025-01-10,East
5,1006,C002,Priya Patel,2025-01-11,West
6,1007,C005,Vikram Singh,2025-01-12,North


### Dataset 2: Order Details

In [3]:
# Create order_details DataFrame
order_details = pd.DataFrame({
    'order_id': [1001, 1002, 1003, 1004, 1005, 1008, 1009],
    'product_id': ['P101', 'P102', 'P103', 'P101', 'P104', 'P105', 'P102'],
    'product_name': ['Laptop', 'Smartphone', 'Headphones', 'Laptop', 
                     'Keyboard', 'Mouse', 'Smartphone'],
    'quantity': [1, 2, 3, 1, 5, 10, 1],
    'price': [45000, 25000, 2000, 45000, 1500, 500, 25000]
})

print("order_details DataFrame:")
display(order_details)

order_details DataFrame:


,order_id,product_id,product_name,quantity,price
0,1001,P101,Laptop,1,45000
1,1002,P102,Smartphone,2,25000
2,1003,P103,Headphones,3,2000
3,1004,P101,Laptop,1,45000
4,1005,P104,Keyboard,5,1500
5,1008,P105,Mouse,10,500
6,1009,P102,Smartphone,1,25000


### Dataset 3: Product Inventory

In [4]:
# Create product_inventory DataFrame
product_inventory = pd.DataFrame({
    'product_id': ['P101', 'P102', 'P103', 'P104', 'P106'],
    'category': ['Electronics', 'Electronics', 'Accessories', 'Accessories', 'Electronics'],
    'stock': [50, 100, 200, 150, 75],
    'warehouse_location': ['Mumbai', 'Delhi', 'Bangalore', 'Kolkata', 'Chennai']
})

print("product_inventory DataFrame:")
display(product_inventory)

product_inventory DataFrame:


,product_id,category,stock,warehouse_location
0,P101,Electronics,50,Mumbai
1,P102,Electronics,100,Delhi
2,P103,Accessories,200,Bangalore
3,P104,Accessories,150,Kolkata
4,P106,Electronics,75,Chennai


### Dataset 4: Additional Orders (for concatenation)

In [5]:
# Create additional_orders DataFrame
additional_orders = pd.DataFrame({
    'order_id': [1010, 1011, 1012],
    'customer_id': ['C006', 'C001', 'C007'],
    'customer_name': ['Anjali Desai', 'Rahul Sharma', 'Rohan Mehta'],
    'order_date': ['2025-01-13', '2025-01-14', '2025-01-15'],
    'region': ['West', 'North', 'South']
})

print("additional_orders DataFrame:")
display(additional_orders)

additional_orders DataFrame:


,order_id,customer_id,customer_name,order_date,region
0,1010,C006,Anjali Desai,2025-01-13,West
1,1011,C001,Rahul Sharma,2025-01-14,North
2,1012,C007,Rohan Mehta,2025-01-15,South


---

# Practice Questions



> this is written by myself, I am first looking at all the dataframes and trying to understand how are they all connceted to each other.


In [36]:
# basic exploration/ lookover to all datasets
# todo 1. see all the DF's and thier columns
# todo 2. check for connecting columns
# todo 3. How can they be connected? (merging or concatenating)

# customers_orders
# order_details
# product_inventory
# additional_orders

# customer order and additional orders = concatenate
# customers details + product details + order details = big merged dataset
# ? check all the datasets by uncommenting their names mentioned above


## Level 1: Basic Concatenation

### Question 1: Vertical Concatenation
**Task**: Concatenate `customers_orders` and `additional_orders` DataFrames vertically to create a complete order history. Reset the index after concatenation.

**Concepts**: `pd.concat()`, `axis=0`, `ignore_index=True`

**Expected Output**: A DataFrame with 10 rows (7 + 3 orders)

In [21]:
orders = pd.concat([customers_orders, additional_orders], ignore_index=True)
orders

,order_id,customer_id,customer_name,order_date,region
0,1001,C001,Rahul Sharma,2025-01-05,North
1,1002,C002,Priya Patel,2025-01-06,West
2,1003,C001,Rahul Sharma,2025-01-08,North
3,1004,C003,Amit Kumar,2025-01-09,South
4,1005,C004,Sneha Reddy,2025-01-10,East
5,1006,C002,Priya Patel,2025-01-11,West
6,1007,C005,Vikram Singh,2025-01-12,North
7,1010,C006,Anjali Desai,2025-01-13,West
8,1011,C001,Rahul Sharma,2025-01-14,North
9,1012,C007,Rohan Mehta,2025-01-15,South


In [66]:
# this is the way where we sustain the indexes of both datasets and conatenate them

orders_with_keys = pd.concat([customers_orders, additional_orders], keys = ['original', 'additional'])
orders_with_keys
# to access elements from both datasets after concatenation with keys
# we can use .loc method

# # ! method 1
# orders_with_keys.loc['original'].iloc[0]

# # ! method 2
# orders_with_keys.loc[('original', 0)]


order_id customer_id customer_name  order_date region
original   0      1001        C001  Rahul Sharma  2025-01-05  North
           1      1002        C002   Priya Patel  2025-01-06   West
           2      1003        C001  Rahul Sharma  2025-01-08  North
           3      1004        C003    Amit Kumar  2025-01-09  South
           4      1005        C004   Sneha Reddy  2025-01-10   East
           5      1006        C002   Priya Patel  2025-01-11   West
           6      1007        C005  Vikram Singh  2025-01-12  North
additional 0      1010        C006  Anjali Desai  2025-01-13   West
           1      1011        C001  Rahul Sharma  2025-01-14  North
           2      1012        C007   Rohan Mehta  2025-01-15  South

### Question 2: Horizontal Concatenation
**Task**: Concatenate `customers_orders` and `order_details` DataFrames horizontally using `axis=1`. Observe what happens with non-matching indices.

**Concepts**: `pd.concat()`, `axis=1`

**Expected Outcome**: Notice how pandas aligns data by index (not by order_id)

In [ ]:
print(customers_orders.shape)
print(order_details.shape)

# since the no. of rows are same, no null values will be thier by horizontal concatenation
pd.concat([customers_orders,order_details], axis = 1)

# ! interesting fact : indexes are not considered as columns in dataframe

(7, 5)
(7, 5)


,order_id,customer_id,customer_name,order_date,region,order_id,product_id,product_name,quantity,price
0,1001,C001,Rahul Sharma,2025-01-05,North,1001,P101,Laptop,1,45000
1,1002,C002,Priya Patel,2025-01-06,West,1002,P102,Smartphone,2,25000
2,1003,C001,Rahul Sharma,2025-01-08,North,1003,P103,Headphones,3,2000
3,1004,C003,Amit Kumar,2025-01-09,South,1004,P101,Laptop,1,45000
4,1005,C004,Sneha Reddy,2025-01-10,East,1005,P104,Keyboard,5,1500
5,1006,C002,Priya Patel,2025-01-11,West,1008,P105,Mouse,10,500
6,1007,C005,Vikram Singh,2025-01-12,North,1009,P102,Smartphone,1,25000


---

## Level 2: Inner and Outer Joins

### Question 3: Inner Join
**Task**: Merge `customers_orders` with `order_details` on `order_id` using an inner join. Count how many records are in the result and explain why.

**Concepts**: `pd.merge()`, `how='inner'`, `on='column_name'`

**Expected Output**: Should have fewer rows than both original DataFrames

In [42]:
customers_orders.merge(order_details,on = 'order_id')

# in this kind of join only those rows which are present in both datasets will be shown
# more precisely the order_id should be present on both in order to map the combined rows

,order_id,customer_id,customer_name,order_date,region,product_id,product_name,quantity,price
0,1001,C001,Rahul Sharma,2025-01-05,North,P101,Laptop,1,45000
1,1002,C002,Priya Patel,2025-01-06,West,P102,Smartphone,2,25000
2,1003,C001,Rahul Sharma,2025-01-08,North,P103,Headphones,3,2000
3,1004,C003,Amit Kumar,2025-01-09,South,P101,Laptop,1,45000
4,1005,C004,Sneha Reddy,2025-01-10,East,P104,Keyboard,5,1500


### Question 4: Outer Join (Full Join)
**Task**: Perform a full outer join between `customers_orders` and `order_details` on `order_id`. Identify which orders exist in one DataFrame but not the other.

**Concepts**: `pd.merge()`, `how='outer'`

**Expected Output**: All orders from both DataFrames, with NaN values where data is missing

In [47]:
customers_orders.merge(order_details,on = 'order_id', how = 'outer')
# sab khichdi aa jayegi
# type(np.nan)

,order_id,customer_id,customer_name,order_date,region,product_id,product_name,quantity,price
0,1001,C001,Rahul Sharma,2025-01-05,North,P101,Laptop,1.0,45000.0
1,1002,C002,Priya Patel,2025-01-06,West,P102,Smartphone,2.0,25000.0
2,1003,C001,Rahul Sharma,2025-01-08,North,P103,Headphones,3.0,2000.0
3,1004,C003,Amit Kumar,2025-01-09,South,P101,Laptop,1.0,45000.0
4,1005,C004,Sneha Reddy,2025-01-10,East,P104,Keyboard,5.0,1500.0
5,1006,C002,Priya Patel,2025-01-11,West,NaN,NaN,NaN,NaN
6,1007,C005,Vikram Singh,2025-01-12,North,NaN,NaN,NaN,NaN
7,1008,NaN,NaN,NaN,NaN,P105,Mouse,10.0,500.0
8,1009,NaN,NaN,NaN,NaN,P102,Smartphone,1.0,25000.0


### Question 5: Left Join
**Task**: Perform a left join with `customers_orders` as the left DataFrame and `order_details` as the right DataFrame. What happens to order_id 1008 and 1009?

**Concepts**: `pd.merge()`, `how='left'`

**Expected Output**: All customer orders preserved, NaN for orders without product details

In [ ]:
customers_orders.merge(order_details,on = 'order_id', how = 'left')

# orders whose customer dtails are present but product details are missing

,order_id,customer_id,customer_name,order_date,region,product_id,product_name,quantity,price
0,1001,C001,Rahul Sharma,2025-01-05,North,P101,Laptop,1.0,45000.0
1,1002,C002,Priya Patel,2025-01-06,West,P102,Smartphone,2.0,25000.0
2,1003,C001,Rahul Sharma,2025-01-08,North,P103,Headphones,3.0,2000.0
3,1004,C003,Amit Kumar,2025-01-09,South,P101,Laptop,1.0,45000.0
4,1005,C004,Sneha Reddy,2025-01-10,East,P104,Keyboard,5.0,1500.0
5,1006,C002,Priya Patel,2025-01-11,West,NaN,NaN,NaN,NaN
6,1007,C005,Vikram Singh,2025-01-12,North,NaN,NaN,NaN,NaN


### Question 6: Right Join
**Task**: Perform a right join with `customers_orders` as the left DataFrame and `order_details` as the right DataFrame. Compare the results with the left join from Question 5.

**Concepts**: `pd.merge()`, `how='right'`

**Expected Output**: All order details preserved, NaN for orders without customer information

In [ ]:
customers_orders.merge(order_details,on = 'order_id', how = 'right')

# orders whose products details are present but customer details are missing

,order_id,customer_id,customer_name,order_date,region,product_id,product_name,quantity,price
0,1001,C001,Rahul Sharma,2025-01-05,North,P101,Laptop,1,45000
1,1002,C002,Priya Patel,2025-01-06,West,P102,Smartphone,2,25000
2,1003,C001,Rahul Sharma,2025-01-08,North,P103,Headphones,3,2000
3,1004,C003,Amit Kumar,2025-01-09,South,P101,Laptop,1,45000
4,1005,C004,Sneha Reddy,2025-01-10,East,P104,Keyboard,5,1500
5,1008,NaN,NaN,NaN,NaN,P105,Mouse,10,500
6,1009,NaN,NaN,NaN,NaN,P102,Smartphone,1,25000


---

## Level 3: Multi-Key Merges and Complex Scenarios

### Question 7: Three-Way Merge
**Task**: Create a comprehensive dataset by merging all three DataFrames:
1. First merge `customers_orders` with `order_details`
2. Then merge the result with `product_inventory`

Use appropriate join types to preserve all order information.

**Concepts**: Sequential merging, choosing appropriate join types

**Expected Output**: A comprehensive view of orders with customer, product, and inventory details

In [63]:
main_inner = customers_orders.merge(order_details, on = 'order_id',).merge(product_inventory, on = 'product_id')
main_inner

#  this is a proper dataset without any missing values which could be created when merging all three datasets

,order_id,customer_id,customer_name,order_date,region,product_id,product_name,quantity,price,category,stock,warehouse_location
0,1001,C001,Rahul Sharma,2025-01-05,North,P101,Laptop,1,45000,Electronics,50,Mumbai
1,1002,C002,Priya Patel,2025-01-06,West,P102,Smartphone,2,25000,Electronics,100,Delhi
2,1003,C001,Rahul Sharma,2025-01-08,North,P103,Headphones,3,2000,Accessories,200,Bangalore
3,1004,C003,Amit Kumar,2025-01-09,South,P101,Laptop,1,45000,Electronics,50,Mumbai
4,1005,C004,Sneha Reddy,2025-01-10,East,P104,Keyboard,5,1500,Accessories,150,Kolkata


In [62]:
main_outer = customers_orders.merge(order_details, on = 'order_id', how='outer').merge(product_inventory, on = 'product_id', how = 'outer')
main_outer


# one hell of a dataset with so many missing values due to outer joins

,order_id,customer_id,customer_name,order_date,region,product_id,product_name,quantity,price,category,stock,warehouse_location
0,1001.0,C001,Rahul Sharma,2025-01-05,North,P101,Laptop,1.0,45000.0,Electronics,50.0,Mumbai
1,1004.0,C003,Amit Kumar,2025-01-09,South,P101,Laptop,1.0,45000.0,Electronics,50.0,Mumbai
2,1002.0,C002,Priya Patel,2025-01-06,West,P102,Smartphone,2.0,25000.0,Electronics,100.0,Delhi
3,1009.0,NaN,NaN,NaN,NaN,P102,Smartphone,1.0,25000.0,Electronics,100.0,Delhi
4,1003.0,C001,Rahul Sharma,2025-01-08,North,P103,Headphones,3.0,2000.0,Accessories,200.0,Bangalore
5,1005.0,C004,Sneha Reddy,2025-01-10,East,P104,Keyboard,5.0,1500.0,Accessories,150.0,Kolkata
6,1008.0,NaN,NaN,NaN,NaN,P105,Mouse,10.0,500.0,NaN,NaN,NaN
7,NaN,NaN,NaN,NaN,NaN,P106,NaN,NaN,NaN,Electronics,75.0,Chennai
8,1006.0,C002,Priya Patel,2025-01-11,West,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,1007.0,C005,Vikram Singh,2025-01-12,North,NaN,NaN,NaN,NaN,NaN,NaN,NaN


### Question 8: Using Indicator Column
**Task**: Use the `indicator=True` parameter when merging `order_details` with `product_inventory` on `product_id`. Analyze the `_merge` column to identify:
- Records that exist in both DataFrames
- Records only in order_details (left_only)
- Records only in product_inventory (right_only)

**Concepts**: `indicator=True`, data quality checking

**Expected Output**: DataFrame with `_merge` column showing the source of each record

In [60]:
order_details.merge(product_inventory, on = 'product_id',how = 'outer', indicator=True)

,order_id,product_id,product_name,quantity,price,category,stock,warehouse_location,_merge
0,1001.0,P101,Laptop,1.0,45000.0,Electronics,50.0,Mumbai,both
1,1004.0,P101,Laptop,1.0,45000.0,Electronics,50.0,Mumbai,both
2,1002.0,P102,Smartphone,2.0,25000.0,Electronics,100.0,Delhi,both
3,1009.0,P102,Smartphone,1.0,25000.0,Electronics,100.0,Delhi,both
4,1003.0,P103,Headphones,3.0,2000.0,Accessories,200.0,Bangalore,both
5,1005.0,P104,Keyboard,5.0,1500.0,Accessories,150.0,Kolkata,both
6,1008.0,P105,Mouse,10.0,500.0,NaN,NaN,NaN,left_only
7,NaN,P106,NaN,NaN,NaN,Electronics,75.0,Chennai,right_only


---

## Level 4: Advanced Operations

### Question 9: Suffix Handling
**Task**: Create a scenario where you have overlapping column names. Merge `customers_orders` with itself on `customer_id` to find repeat customers. Use the `suffixes` parameter to distinguish between first and second orders.

**Concepts**: `suffixes=('_first', '_second')`, self-joins

**Expected Output**: DataFrame showing customers with multiple orders

In [ ]:
# Your code here


### Question 10: Conditional Analysis
**Task**: Perform an outer join of `customers_orders` and `order_details`. Then identify and filter rows where customer information exists but no product details are available (indicating cancelled or pending orders).

**Concepts**: Outer join + filtering with `.isna()`

**Expected Output**: Orders from customers_orders that don't have corresponding entries in order_details

In [ ]:
# Your code here


### Question 11: Aggregate After Merge
**Task**: 
1. Merge all three datasets (`customers_orders`, `order_details`, `product_inventory`)
2. Calculate the total revenue by region and product category
3. Use `.groupby()` and aggregation functions

**Concepts**: Merging + GroupBy + Aggregation

**Expected Output**: Revenue breakdown by region and category

In [65]:
main_inner.groupby(['region', 'category']).price.sum()

region  category   
East    Accessories     1500
North   Accessories     2000
        Electronics    45000
South   Electronics    45000
West    Electronics    25000
Name: price, dtype: int64

### Question 12: Multiple Concatenations and Merges
**Task**:
1. Concatenate `customers_orders` and `additional_orders`
2. Merge the result with `order_details` using an inner join
3. Merge again with the same `order_details` using an outer join
4. Compare the number of rows in both results

**Concepts**: Combining concat and merge operations

**Expected Output**: Two merged DataFrames to compare

In [69]:
# a combined data set of both original and additional orders dataset is already there in "orders" dataframe
orders
# honestly bohot easy question hai, you can leave it 😉😉

,order_id,customer_id,customer_name,order_date,region
0,1001,C001,Rahul Sharma,2025-01-05,North
1,1002,C002,Priya Patel,2025-01-06,West
2,1003,C001,Rahul Sharma,2025-01-08,North
3,1004,C003,Amit Kumar,2025-01-09,South
4,1005,C004,Sneha Reddy,2025-01-10,East
5,1006,C002,Priya Patel,2025-01-11,West
6,1007,C005,Vikram Singh,2025-01-12,North
7,1010,C006,Anjali Desai,2025-01-13,West
8,1011,C001,Rahul Sharma,2025-01-14,North
9,1012,C007,Rohan Mehta,2025-01-15,South


---

## Bonus Challenge

### Question 13: Data Quality Report
**Task**: Create a comprehensive data quality report that shows:
1. Orders without customer details (orphaned orders in order_details)
2. Products ordered but not in inventory
3. Customers with orders but no product details
4. Summary statistics: Total matched vs unmatched records

Use the `indicator=True` parameter across multiple merges.

**Concepts**: Multiple merges with indicators, data quality analysis

**Expected Output**: A detailed report identifying data inconsistencies

In [ ]:
# Your code here


---

## Notes and Key Takeaways

After completing all questions, write down your key learnings:

- What's the difference between concat and merge?
- When should you use inner vs outer joins?
- How does the indicator parameter help with data quality?
- What happens to duplicate column names during merge?
- When is concatenation with axis=1 useful vs axis=0?

**Your notes below:**

---

## Additional Practice Ideas

If you want more practice:
1. Try merging on multiple columns simultaneously
2. Experiment with different index alignments
3. Create your own datasets with overlapping/non-overlapping keys
4. Practice with datetime columns and merge based on time ranges
5. Explore `merge_asof()` for time-series data

Good luck with your practice! 🚀